### ISSUE TITLE
Case Study 3 Notes 

### ISSUE THREAD

**Issue by Sabrina-Olmo** [DTS350Fall2022/dickersonm#3]
2 stars:
-graphs show the data clearly and are very organized 
- She was able to create a new smaller data frame to build her second graph from

1 wish:
-legend title for population was not changed to reflect Population(100k)

Additional questions:
-Does the population alone affect life expectancy?
-How does each specific country's GDP per Capita relate to life expectancy? Rather than faceting by continent, facet by country.

**Comment by mallorydickerson** [comment]
issue fixed
